name: FT Scraper Daily Job

on:
  schedule:
    - cron: '0 0 * * *'  # run daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write   # allow pushing changes to the repo

jobs:
  daily-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install

      - name: Run daily job
        run: python -m src.scheduler.daily_job

      - name: Commit and push generated presentation
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/presentations/*.pptx || echo "No new presentations to add"
          git commit -m "Add daily presentation [$(date +'%Y-%m-%d')]" || echo "No changes to commit"
          git push
