name: FT Scraper Daily Job

on:
  schedule:
    - cron: '0 0 * * *'  # run daily at midnight UTC
  workflow_dispatch:

jobs:
  daily-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install
      
      - name: Install Playwright dependencies
        run: sudo apt-get update && sudo apt-get install -y \
          libgtk-4-1 \
          libgraphene-1.0-0 \
          libwoff2-1 \
          libvpx9 \
          libevent-2.1-7 \
          libopus0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-libav \
          libflite1 \
          libavif16 \
          libharfbuzz-icu0 \
          libsecret-1-0 \
          libhyphen0 \
          libgles2 \
          libx264-160

      - name: Run daily job
        run: python -m ft_scraper.scheduler.daily_job
